### PR TITLE
Basic ?tronky command

### LINKED ISSUE #54: ?givetronky command as requested by a lot of people
ah yes, the tronky meme. a random image that soon became a meme and then an emoji. why not make it a command to give others a tronky? And if you give it to more than 2 people, Q-Bot will say thay you can't afford all the tronkys.

### PR DESCRIPTION
**Pull request by Hyperfresh**
This is a really, **really** botched-up tronky command and needs some cleaning if it was to actually be implemented (I can happily do that if this merge gets the green light).

This PR addresses #54.

### CODE REVIEW

**Review by iwa — CHANGES_REQUESTED** [review]
please rebase your PR cause you're using a quite old version of the `actions.ts` file :/

**Comment by Hyperfresh** [comment]
ok, will do and have a look

**Comment by Hyperfresh** [comment]
ok fixing it now

**Comment by Hyperfresh** [comment]
Not sure what CodeFactor's mad about there. By the looks of it, just complex code (not 100% sure how to fix that.)

This should be good for you to have another look now @iwa

**Review by iwa — APPROVED** [review]

**Pull request merged**
